parameters:
    moop.fs.cache.array.class: Doctrine\Common\Cache\ArrayCache
    moop.fs.cache.redis.class: Doctrine\Common\Cache\RedisCache

services:
    cache.redis:
        class: Redis
        calls:
            - [connect, ["%moop.fs.cache.redis.host%", "%moop.fs.cache.redis.port%"]]
    
    moop.fs.cache.array:
        class: "%moop.fs.cache.array.class%"
    
    moop.fs.cache.redis:
        class: "%moop.fs.cache.redis.class%"
        calls:
            - [setRedis, [@cache.redis]]
    