imports:
    - { resource: cache-providers.yml }

services:
    moop.fat_secret.api:
        class: Moop\Bundle\FatSecretBundle\API\FatSecret
        arguments: ["@moop.fs.cache", "@moop.oauth.version_one", "%moop.fs.api_base_url%"]
        calls:
            - [setConsumerTokens, ["%moop.fs.consumer_key%", "%moop.fs.consumer_secret%"]]