imports:
    - { resource: cache-providers.yml }

services:
    moop.oauth.version_one:
        class:     Moop\Bundle\FatSecretBundle\Utility\OAuth
        arguments: ["@buzz.browser", "%moop.fs.consumer_key%", "%moop.fs.consumer_secret%"]
    
    moop.fat_secret.api:
        class: Moop\Bundle\FatSecretBundle\API\FatSecret
        arguments: ["@moop.fat_secret.cache", "@moop.oauth.version_one", "%moop.fs.api_base_url%"]
    
    buzz.browser:
        class: Buzz\Browser
        arguments: ["@buzz.client.curl"]
    
    buzz.client.curl:
        class: Buzz\Client\Curl