imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

parameters:
    fs.oauth.consumer_key:    ~
    fs.oauth.consumer_secret: ~

moop_fat_secret:
    consumer_key:        "%fs.oauth.consumer_key%"
    consumer_secret:     "%fs.oauth.consumer_secret%"
    cache_provider_type: array
    cache_providers:
        array:
            id:   @moop.fs.cache.array
        redis:
            id:   @moop.fs.cache.redis
            host: localhost
            port: 6379


framework:
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['php']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true
